spring.datasource.url=jdbc:postgresql://dpg-d79nnuaa214c73av3f0g-a.oregon-postgres.render.com:5432/task_db_byk0
spring.datasource.username=task_db_byk0_user
spring.datasource.password=s77Ae2u8eza0bgd9lcQek5xSVP9ZWwCM

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}