/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.50
 * Generated at: 2026-02-15 13:41:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.include;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"utf-8\">\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("        <title>Solid State</title>\n");
      out.write("        <link href=\"assets/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/ionicons.min.css\">\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Istok+Web:400,400i,700,700i\" rel=\"stylesheet\">\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Roboto:300,300i,400\" rel=\"stylesheet\">\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=PT+Sans\" rel=\"stylesheet\">\n");
      out.write("        <link href=\"assets/css/main.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    </head>\n");
      out.write("<body>\n");
      out.write("    <!-- preloader -->\n");
      out.write("    <div id=\"preloader\"></div>\n");
      out.write("    <!-- end of preloader -->\n");
      out.write("\n");
      out.write("    <div class=\"body-content\" style=\"display:none;\">\n");
      out.write("        <div class=\"navbar-solid-state\">\n");
      out.write("             <!-- Header -->\n");
      out.write("            <header id=\"header\" class=\"alt\">\n");
      out.write("                <!-- <h1><a href=\"index.html\" class=\"a-transparent\">Solid State</a></h1> -->\n");
      out.write("                <nav>\n");
      out.write("                    <a href=\"#menu\" class=\"a-menu\">Menu <i class=\"ion-android-menu\"></i> </a>\n");
      out.write("                </nav>\n");
      out.write("            </header>\n");
      out.write("\n");
      out.write("            <!-- Menu -->\n");
      out.write("            <nav id=\"menu\">\n");
      out.write("                <div class=\"inner\">\n");
      out.write("                    <h2>Menu</h2>\n");
      out.write("                    <ul class=\"links\">\n");
      out.write("                        <li><a href=\"index.html\">Home</a></li>\n");
      out.write("                        <li><a href=\"elements.html\">Elements</a></li>\n");
      out.write("                        <!-- <li><a href=\"#\">Log In</a></li>\n");
      out.write("                        <li><a href=\"#\">Sign Up</a></li> -->\n");
      out.write("                    </ul>\n");
      out.write("                    <a href=\"#\" class=\"close\">Close</a>\n");
      out.write("                </div>\n");
      out.write("            </nav>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <section id=\"banner\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-md-12\">\n");
      out.write("                        <h2>MAX OUT YOUR USER EXPERIENCE</h2>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-md-12\"> \n");
      out.write("                        <p>ANOTHER FREE + FULLY RESPONSIVE SITE TEMPLATE BY <a href=\"http://www.themewagon.com\">THEMEWAGON</a></p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-md-12\">\n");
      out.write("                        <a href=\"#\" class=\"btn btn-banner\">DEFAULT</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <section id=\"one\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"one-features\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-md-8\">\n");
      out.write("                            <div class=\"section-highlight\">\n");
      out.write("                                <h2>BEST SPORTS HEADPHONE EVER</h2>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"section-details\">\n");
      out.write("                                <p>\n");
      out.write("                                    Lorem ipsum dolor sit amet, etiam lorem adipiscing elit. Cras turpis ante, nullam sit amet turpis non, sollicitudin posuere urna. Mauris id tellus arcu. Nunc vehicula id nulla dignissim dapibus. Nullam ultrices, neque et faucibus viverra, ex nulla cursus.\n");
      out.write("                                </p>\n");
      out.write("                                <a href=\"#\" class=\"btn btn-learn-more\">LEARN MORE <i class=\"ion-ios-arrow-right\"></i></a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-4\">\n");
      out.write("                            <img src=\"assets/images/03_headephone.png\" alt=\"Responsive image\" class=\"img-responsive\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <section id=\"two\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"two-features\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-md-4\">\n");
      out.write("                        <img src=\"assets/images/04_shoe.png\" alt=\"Responsive image\" class=\"img-responsive\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-8\">\n");
      out.write("                            <div class=\"section-highlight\">\n");
      out.write("                                <h2>WHY YOU LIKE OUR SHOES?</h2>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"section-details\">\n");
      out.write("                                <p>\n");
      out.write("                                    Lorem ipsum dolor sit amet, etiam lorem adipiscing elit. Cras turpis ante, nullam sit amet turpis non, sollicitudin posuere urna. Mauris id tellus arcu. Nunc vehicula id nulla dignissim dapibus. Nullam ultrices, neque et faucibus viverra, ex nulla cursus.\n");
      out.write("                                </p>\n");
      out.write("                                <a href=\"#\" class=\"btn btn-learn-more\">LEARN MORE <i class=\"ion-ios-arrow-right\"></i></a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <section id=\"three\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"three-features\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-md-8\">\n");
      out.write("                            <div class=\"section-highlight\">\n");
      out.write("                                <h2>YANKEES BASEBALL CAP</h2>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"section-details\">\n");
      out.write("                                <p>\n");
      out.write("                                    Lorem ipsum dolor sit amet, etiam lorem adipiscing elit. Cras turpis ante, nullam sit amet turpis non, sollicitudin posuere urna. Mauris id tellus arcu. Nunc vehicula id nulla dignissim dapibus. Nullam ultrices, neque et faucibus viverra, ex nulla cursus.\n");
      out.write("                                </p>\n");
      out.write("                                <a href=\"#\" class=\"btn btn-learn-more\">LEARN MORE <i class=\"ion-ios-arrow-right\"></i></a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-4\">\n");
      out.write("                            <img src=\"assets/images/05_cap.png\" alt=\"Responsive image\" class=\"img-responsive\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <section id=\"four\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <div class=\"four-top\">\n");
      out.write("                        <div class=\"section-heading\">\n");
      out.write("                            <div class=\"title\">\n");
      out.write("                                <div class=\"row\">\n");
      out.write("                                    <div class=\"col-md-12\">\n");
      out.write("                                        <h2>CHECK OUR SERVICES</h2>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <div class=\"subtitle\">\n");
      out.write("                                <div class=\"row\">                                       \n");
      out.write("                                    <div class=\"col-md-9 col-md-offset-1\">\n");
      out.write("                                        <p>\n");
      out.write("                                            Lorem ipsum dolor sit amet, etiam lorem adipiscing elit. Cras turpis ante, nullam sit amet turpis non, sollicitudin posuere urnamauris id tellus arcu.\n");
      out.write("                                        </p>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-md-6\">\n");
      out.write("                            <div class=\"four-features four-features-left-bottom\">\n");
      out.write("                                <div class=\"features-img\">\n");
      out.write("                                    <img src=\"assets/images/07.jpg\" alt=\"Responsive image\" class=\"img-responsive\">\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"features-content\">\n");
      out.write("                                    <h3>MOUNTAIN HIKING</h3>\n");
      out.write("                                    <p>\n");
      out.write("                                    Lorem ipsum dolor sit amet, etiam lorem adipiscing elit. Cras turpis ante, nullam sit amet turpis Nunc sollicitudin posuere urna. Mauris id tellus arcu. Nunc vehicula id nulla\n");
      out.write("                                    </p>\n");
      out.write("                                    <a href=\"#\" class=\"btn btn-learn-more\">LEARN MORE <i class=\"ion-ios-arrow-right\"></i></a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-6\">\n");
      out.write("                            <div class=\"four-features four-features-right-bottom\">\n");
      out.write("                                <img src=\"assets/images/08.jpg\" alt=\"Responsive image\" class=\"img-responsive\">\n");
      out.write("                                <div class=\"features-content\">\n");
      out.write("                                    <h3>SHOE SERVICES</h3>\n");
      out.write("                                    <p>\n");
      out.write("                                    Lorem ipsum dolor sit amet, etiam lorem adipiscing elit. Cras turpis ante, nullam sit amet turpis Nunc sollicitudin posuere urna. Mauris id tellus arcu. Nunc vehicula id nulla\n");
      out.write("                                    </p>\n");
      out.write("                                    <a href=\"#\" class=\"btn btn-learn-more\">LEARN MORE <i class=\"ion-ios-arrow-right\"></i></a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-md-6\">\n");
      out.write("                            <div class=\"four-features four-features-left-top\">\n");
      out.write("                            <img src=\"assets/images/09.jpg\"  alt=\"Responsive image\" class=\"img-responsive\">\n");
      out.write("                                <div class=\"features-content\">\n");
      out.write("                                    <h3>MOUNTAIN VISION</h3>\n");
      out.write("                                    <p>\n");
      out.write("                                    Lorem ipsum dolor sit amet, etiam lorem adipiscing elit. Cras turpis ante, nullam sit amet turpis Nunc sollicitudin posuere urna. Mauris id tellus arcu. Nunc vehicula id nulla\n");
      out.write("                                    </p>\n");
      out.write("                                    <a href=\"#\" class=\"btn btn-learn-more\">\n");
      out.write("                                    LEARN MORE <i class=\"ion-ios-arrow-right\"></i>\n");
      out.write("                                    </a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-6\">\n");
      out.write("                            <div class=\"four-features four-features-right-top\">\n");
      out.write("                                <img src=\"assets/images/10.jpg\" alt=\"Responsive image\" class=\"img-responsive\">\n");
      out.write("                                <div class=\"features-content\">\n");
      out.write("                                    <h3>LIFE IN ADVENTURE</h3>\n");
      out.write("                                    <p>\n");
      out.write("                                    Lorem ipsum dolor sit amet, etiam lorem adipiscing elit. Cras turpis ante, nullam sit amet turpis Nunc sollicitudin posuere urna. Mauris id tellus arcu. Nunc vehicula id nulla\n");
      out.write("                                    </p>\n");
      out.write("                                    <a href=\"#\" class=\"btn btn-learn-more\">\n");
      out.write("                                    LEARN MORE <i class=\"ion-ios-arrow-right\"></i>\n");
      out.write("                                    </a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-md-12\">\n");
      out.write("                            <a href=\"#\" class=\"btn btn-expand-all\">EXPAND ALL</a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <section id=\"footer\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"footer-top\">\n");
      out.write("                    <div class=\"section-heading\">\n");
      out.write("                        <div class=\"title\">\n");
      out.write("                            <div class=\"row\">\n");
      out.write("                                <div class=\"col-md-12\">\n");
      out.write("                                <h2>GET IN TOUCH</h2>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"subtitle\">\n");
      out.write("                            <div class=\"row\">\n");
      out.write("                                <div class=\"col-md-9 col-md-offset-1\">\n");
      out.write("                                    <p>\n");
      out.write("                                    Demo UI\n");
      out.write("                                    </p>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"footer-features\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-md-6\">\n");
      out.write("                            <form>\n");
      out.write("                                <div class=\"form-group\">\n");
      out.write("                                    <input type=\"text\" name=\"name name\" class=\"form-control form-footer\" placeholder=\"Name\" required=\"\">\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"form-group\">\n");
      out.write("                                    <input type=\"email\" required=\"\" class=\"form-control form-footer\" placeholder=\"Email\">\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"form-group\">\n");
      out.write("                                    <textarea class=\"form-control form-footer\" rows=\"5\" placeholder=\"Message\"></textarea>\n");
      out.write("                                </div>\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-solid-state\">Send Message</button>\n");
      out.write("                            </form>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-6\">\n");
      out.write("                            <div class=\"footer-list\">\n");
      out.write("                                <ul class=\"list-unstyled\">\n");
      out.write("                                    <li class=\"list-table\">\n");
      out.write("                                        <i class=\"ion-ios-home\"></i><p>Untitled Inc 1234 Somewhere Road Suite #2894 Nashville, TN 00000-0000</p>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li class=\"list-table\">\n");
      out.write("                                        <i class=\"ion-android-call\"></i><p>(+440) 103-5554</p>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li class=\"list-table\">\n");
      out.write("                                        <i class=\"ion-email\"></i><p>information@mail.com</p>\n");
      out.write("                                    </li>\n");
      out.write("                                </ul>\n");
      out.write("                                <div class=\"list-solid-state\">\n");
      out.write("                                    <ul class=\"list-inline\">\n");
      out.write("                                        <li>\n");
      out.write("                                            <a href=\"#\"><i class=\"ion-social-facebook icon-facebook\"></i></a>\n");
      out.write("                                        </li>\n");
      out.write("                                        <li>\n");
      out.write("                                            <a href=\"#\"><i class=\"ion-social-twitter icon-twitter\"></i></a>\n");
      out.write("                                        </li>\n");
      out.write("                                        <li>\n");
      out.write("                                            <a href=\"#\"><i class=\"ion-social-linkedin icon-linkedin\"></i></a>\n");
      out.write("                                        </li>\n");
      out.write("                                        <li>\n");
      out.write("                                            <i class=\"ion-aperture icon-aperture\"></i>\n");
      out.write("                                        </li>\n");
      out.write("                                        <li>\n");
      out.write("                                            <i class=\"ion-social-rss icon-rss\"></i>\n");
      out.write("                                        </li>\n");
      out.write("                                    </ul>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"footer-bottom\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-md-12\">\n");
      out.write("                            <p>&copy; TECHNEXT 2016. ALL RIGHTS RESERVED BY <a href=\"http://www.themewagon.com\" target=\"_blank\">THEMEWAGON</a></p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script src=\"assets/js/jquery.min.js\"></script>\n");
      out.write("    <script src=\"assets/js/bootstrap.min.js\"></script>\n");
      out.write("    <script src=\"assets/js/main.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("  \n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
